# Generated by Django 2.1.7 on 2019-04-19 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo2', '0003_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['age', '-sname']},
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
